// Generated by gencpp from file jetbotmini_msgs/Buzzer.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_BUZZER_H
#define JETBOTMINI_MSGS_MESSAGE_BUZZER_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/BuzzerRequest.h>
#include <jetbotmini_msgs/BuzzerResponse.h>


namespace jetbotmini_msgs
{

struct Buzzer
{

typedef BuzzerRequest Request;
typedef BuzzerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Buzzer
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::Buzzer > {
  static const char* value()
  {
    return "32ecc8168750cdefd185aff218d2ce5e";
  }

  static const char* value(const ::jetbotmini_msgs::Buzzer&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::Buzzer > {
  static const char* value()
  {
    return "jetbotmini_msgs/Buzzer";
  }

  static const char* value(const ::jetbotmini_msgs::Buzzer&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::BuzzerRequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Buzzer >
template<>
struct MD5Sum< ::jetbotmini_msgs::BuzzerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Buzzer >::value();
  }
  static const char* value(const ::jetbotmini_msgs::BuzzerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::BuzzerRequest> should match
// service_traits::DataType< ::jetbotmini_msgs::Buzzer >
template<>
struct DataType< ::jetbotmini_msgs::BuzzerRequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Buzzer >::value();
  }
  static const char* value(const ::jetbotmini_msgs::BuzzerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::BuzzerResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Buzzer >
template<>
struct MD5Sum< ::jetbotmini_msgs::BuzzerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Buzzer >::value();
  }
  static const char* value(const ::jetbotmini_msgs::BuzzerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::BuzzerResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::Buzzer >
template<>
struct DataType< ::jetbotmini_msgs::BuzzerResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Buzzer >::value();
  }
  static const char* value(const ::jetbotmini_msgs::BuzzerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_BUZZER_H
