// Generated by gencpp from file jetbotmini_msgs/CamDevice.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_CAMDEVICE_H
#define JETBOTMINI_MSGS_MESSAGE_CAMDEVICE_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/CamDeviceRequest.h>
#include <jetbotmini_msgs/CamDeviceResponse.h>


namespace jetbotmini_msgs
{

struct CamDevice
{

typedef CamDeviceRequest Request;
typedef CamDeviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CamDevice
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::CamDevice > {
  static const char* value()
  {
    return "8be1511d89aeca50b4c34cbc069c61f5";
  }

  static const char* value(const ::jetbotmini_msgs::CamDevice&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::CamDevice > {
  static const char* value()
  {
    return "jetbotmini_msgs/CamDevice";
  }

  static const char* value(const ::jetbotmini_msgs::CamDevice&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::CamDeviceRequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::CamDevice >
template<>
struct MD5Sum< ::jetbotmini_msgs::CamDeviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::CamDevice >::value();
  }
  static const char* value(const ::jetbotmini_msgs::CamDeviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::CamDeviceRequest> should match
// service_traits::DataType< ::jetbotmini_msgs::CamDevice >
template<>
struct DataType< ::jetbotmini_msgs::CamDeviceRequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::CamDevice >::value();
  }
  static const char* value(const ::jetbotmini_msgs::CamDeviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::CamDeviceResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::CamDevice >
template<>
struct MD5Sum< ::jetbotmini_msgs::CamDeviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::CamDevice >::value();
  }
  static const char* value(const ::jetbotmini_msgs::CamDeviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::CamDeviceResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::CamDevice >
template<>
struct DataType< ::jetbotmini_msgs::CamDeviceResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::CamDevice >::value();
  }
  static const char* value(const ::jetbotmini_msgs::CamDeviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_CAMDEVICE_H
