// Generated by gencpp from file jetbotmini_msgs/CamDeviceRequest.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_CAMDEVICEREQUEST_H
#define JETBOTMINI_MSGS_MESSAGE_CAMDEVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbotmini_msgs
{
template <class ContainerAllocator>
struct CamDeviceRequest_
{
  typedef CamDeviceRequest_<ContainerAllocator> Type;

  CamDeviceRequest_()
    : GetGev()  {
    }
  CamDeviceRequest_(const ContainerAllocator& _alloc)
    : GetGev(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _GetGev_type;
  _GetGev_type GetGev;





  typedef boost::shared_ptr< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CamDeviceRequest_

typedef ::jetbotmini_msgs::CamDeviceRequest_<std::allocator<void> > CamDeviceRequest;

typedef boost::shared_ptr< ::jetbotmini_msgs::CamDeviceRequest > CamDeviceRequestPtr;
typedef boost::shared_ptr< ::jetbotmini_msgs::CamDeviceRequest const> CamDeviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.GetGev == rhs.GetGev;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetbotmini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "007978485738a378d13c2abf3d31a3ee";
  }

  static const char* value(const ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x007978485738a378ULL;
  static const uint64_t static_value2 = 0xd13c2abf3d31a3eeULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbotmini_msgs/CamDeviceRequest";
  }

  static const char* value(const ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"string GetGev\n"
;
  }

  static const char* value(const ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.GetGev);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CamDeviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbotmini_msgs::CamDeviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "GetGev: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.GetGev);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_CAMDEVICEREQUEST_H
