// Generated by gencpp from file jetbotmini_msgs/Headlight.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_HEADLIGHT_H
#define JETBOTMINI_MSGS_MESSAGE_HEADLIGHT_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/HeadlightRequest.h>
#include <jetbotmini_msgs/HeadlightResponse.h>


namespace jetbotmini_msgs
{

struct Headlight
{

typedef HeadlightRequest Request;
typedef HeadlightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Headlight
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::Headlight > {
  static const char* value()
  {
    return "39cb7e9dbd56dfa74d38f52f3463c89d";
  }

  static const char* value(const ::jetbotmini_msgs::Headlight&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::Headlight > {
  static const char* value()
  {
    return "jetbotmini_msgs/Headlight";
  }

  static const char* value(const ::jetbotmini_msgs::Headlight&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::HeadlightRequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Headlight >
template<>
struct MD5Sum< ::jetbotmini_msgs::HeadlightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Headlight >::value();
  }
  static const char* value(const ::jetbotmini_msgs::HeadlightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::HeadlightRequest> should match
// service_traits::DataType< ::jetbotmini_msgs::Headlight >
template<>
struct DataType< ::jetbotmini_msgs::HeadlightRequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Headlight >::value();
  }
  static const char* value(const ::jetbotmini_msgs::HeadlightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::HeadlightResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Headlight >
template<>
struct MD5Sum< ::jetbotmini_msgs::HeadlightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Headlight >::value();
  }
  static const char* value(const ::jetbotmini_msgs::HeadlightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::HeadlightResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::Headlight >
template<>
struct DataType< ::jetbotmini_msgs::HeadlightResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Headlight >::value();
  }
  static const char* value(const ::jetbotmini_msgs::HeadlightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_HEADLIGHT_H
