// Generated by gencpp from file jetbotmini_msgs/LEDBLUERequest.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_LEDBLUEREQUEST_H
#define JETBOTMINI_MSGS_MESSAGE_LEDBLUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbotmini_msgs
{
template <class ContainerAllocator>
struct LEDBLUERequest_
{
  typedef LEDBLUERequest_<ContainerAllocator> Type;

  LEDBLUERequest_()
    : ledblue(0)  {
    }
  LEDBLUERequest_(const ContainerAllocator& _alloc)
    : ledblue(0)  {
  (void)_alloc;
    }



   typedef int32_t _ledblue_type;
  _ledblue_type ledblue;





  typedef boost::shared_ptr< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> const> ConstPtr;

}; // struct LEDBLUERequest_

typedef ::jetbotmini_msgs::LEDBLUERequest_<std::allocator<void> > LEDBLUERequest;

typedef boost::shared_ptr< ::jetbotmini_msgs::LEDBLUERequest > LEDBLUERequestPtr;
typedef boost::shared_ptr< ::jetbotmini_msgs::LEDBLUERequest const> LEDBLUERequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator2> & rhs)
{
  return lhs.ledblue == rhs.ledblue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetbotmini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f90e4abf82e09b8375aec3cc112c4be9";
  }

  static const char* value(const ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf90e4abf82e09b83ULL;
  static const uint64_t static_value2 = 0x75aec3cc112c4be9ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbotmini_msgs/LEDBLUERequest";
  }

  static const char* value(const ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"int32 ledblue\n"
;
  }

  static const char* value(const ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ledblue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LEDBLUERequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbotmini_msgs::LEDBLUERequest_<ContainerAllocator>& v)
  {
    s << indent << "ledblue: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ledblue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_LEDBLUEREQUEST_H
