// Generated by gencpp from file jetbotmini_msgs/LEDBLUE.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_LEDBLUE_H
#define JETBOTMINI_MSGS_MESSAGE_LEDBLUE_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/LEDBLUERequest.h>
#include <jetbotmini_msgs/LEDBLUEResponse.h>


namespace jetbotmini_msgs
{

struct LEDBLUE
{

typedef LEDBLUERequest Request;
typedef LEDBLUEResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LEDBLUE
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::LEDBLUE > {
  static const char* value()
  {
    return "47351cc96df61967f8e7918f3664cc29";
  }

  static const char* value(const ::jetbotmini_msgs::LEDBLUE&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::LEDBLUE > {
  static const char* value()
  {
    return "jetbotmini_msgs/LEDBLUE";
  }

  static const char* value(const ::jetbotmini_msgs::LEDBLUE&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::LEDBLUERequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::LEDBLUE >
template<>
struct MD5Sum< ::jetbotmini_msgs::LEDBLUERequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::LEDBLUE >::value();
  }
  static const char* value(const ::jetbotmini_msgs::LEDBLUERequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::LEDBLUERequest> should match
// service_traits::DataType< ::jetbotmini_msgs::LEDBLUE >
template<>
struct DataType< ::jetbotmini_msgs::LEDBLUERequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::LEDBLUE >::value();
  }
  static const char* value(const ::jetbotmini_msgs::LEDBLUERequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::LEDBLUEResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::LEDBLUE >
template<>
struct MD5Sum< ::jetbotmini_msgs::LEDBLUEResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::LEDBLUE >::value();
  }
  static const char* value(const ::jetbotmini_msgs::LEDBLUEResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::LEDBLUEResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::LEDBLUE >
template<>
struct DataType< ::jetbotmini_msgs::LEDBLUEResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::LEDBLUE >::value();
  }
  static const char* value(const ::jetbotmini_msgs::LEDBLUEResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_LEDBLUE_H
