// Generated by gencpp from file jetbotmini_msgs/LEDGREE.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_LEDGREE_H
#define JETBOTMINI_MSGS_MESSAGE_LEDGREE_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/LEDGREERequest.h>
#include <jetbotmini_msgs/LEDGREEResponse.h>


namespace jetbotmini_msgs
{

struct LEDGREE
{

typedef LEDGREERequest Request;
typedef LEDGREEResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LEDGREE
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::LEDGREE > {
  static const char* value()
  {
    return "86491fb7054f298518353955ffe73456";
  }

  static const char* value(const ::jetbotmini_msgs::LEDGREE&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::LEDGREE > {
  static const char* value()
  {
    return "jetbotmini_msgs/LEDGREE";
  }

  static const char* value(const ::jetbotmini_msgs::LEDGREE&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::LEDGREERequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::LEDGREE >
template<>
struct MD5Sum< ::jetbotmini_msgs::LEDGREERequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::LEDGREE >::value();
  }
  static const char* value(const ::jetbotmini_msgs::LEDGREERequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::LEDGREERequest> should match
// service_traits::DataType< ::jetbotmini_msgs::LEDGREE >
template<>
struct DataType< ::jetbotmini_msgs::LEDGREERequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::LEDGREE >::value();
  }
  static const char* value(const ::jetbotmini_msgs::LEDGREERequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::LEDGREEResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::LEDGREE >
template<>
struct MD5Sum< ::jetbotmini_msgs::LEDGREEResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::LEDGREE >::value();
  }
  static const char* value(const ::jetbotmini_msgs::LEDGREEResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::LEDGREEResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::LEDGREE >
template<>
struct DataType< ::jetbotmini_msgs::LEDGREEResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::LEDGREE >::value();
  }
  static const char* value(const ::jetbotmini_msgs::LEDGREEResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_LEDGREE_H
