// Generated by gencpp from file jetbotmini_msgs/LEDGREERequest.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_LEDGREEREQUEST_H
#define JETBOTMINI_MSGS_MESSAGE_LEDGREEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbotmini_msgs
{
template <class ContainerAllocator>
struct LEDGREERequest_
{
  typedef LEDGREERequest_<ContainerAllocator> Type;

  LEDGREERequest_()
    : ledgree(0)  {
    }
  LEDGREERequest_(const ContainerAllocator& _alloc)
    : ledgree(0)  {
  (void)_alloc;
    }



   typedef int32_t _ledgree_type;
  _ledgree_type ledgree;





  typedef boost::shared_ptr< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> const> ConstPtr;

}; // struct LEDGREERequest_

typedef ::jetbotmini_msgs::LEDGREERequest_<std::allocator<void> > LEDGREERequest;

typedef boost::shared_ptr< ::jetbotmini_msgs::LEDGREERequest > LEDGREERequestPtr;
typedef boost::shared_ptr< ::jetbotmini_msgs::LEDGREERequest const> LEDGREERequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator2> & rhs)
{
  return lhs.ledgree == rhs.ledgree;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetbotmini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68c60c31d96409d9417a5b98e97a1dad";
  }

  static const char* value(const ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68c60c31d96409d9ULL;
  static const uint64_t static_value2 = 0x417a5b98e97a1dadULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbotmini_msgs/LEDGREERequest";
  }

  static const char* value(const ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"int32 ledgree\n"
;
  }

  static const char* value(const ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ledgree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LEDGREERequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbotmini_msgs::LEDGREERequest_<ContainerAllocator>& v)
  {
    s << indent << "ledgree: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ledgree);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_LEDGREEREQUEST_H
