// Generated by gencpp from file jetbotmini_msgs/Motor.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_MOTOR_H
#define JETBOTMINI_MSGS_MESSAGE_MOTOR_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/MotorRequest.h>
#include <jetbotmini_msgs/MotorResponse.h>


namespace jetbotmini_msgs
{

struct Motor
{

typedef MotorRequest Request;
typedef MotorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Motor
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::Motor > {
  static const char* value()
  {
    return "d173c13dad4a63ef401052b6062c05e5";
  }

  static const char* value(const ::jetbotmini_msgs::Motor&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::Motor > {
  static const char* value()
  {
    return "jetbotmini_msgs/Motor";
  }

  static const char* value(const ::jetbotmini_msgs::Motor&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::MotorRequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Motor >
template<>
struct MD5Sum< ::jetbotmini_msgs::MotorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Motor >::value();
  }
  static const char* value(const ::jetbotmini_msgs::MotorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::MotorRequest> should match
// service_traits::DataType< ::jetbotmini_msgs::Motor >
template<>
struct DataType< ::jetbotmini_msgs::MotorRequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Motor >::value();
  }
  static const char* value(const ::jetbotmini_msgs::MotorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::MotorResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Motor >
template<>
struct MD5Sum< ::jetbotmini_msgs::MotorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Motor >::value();
  }
  static const char* value(const ::jetbotmini_msgs::MotorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::MotorResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::Motor >
template<>
struct DataType< ::jetbotmini_msgs::MotorResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Motor >::value();
  }
  static const char* value(const ::jetbotmini_msgs::MotorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_MOTOR_H
