// Generated by gencpp from file jetbotmini_msgs/MotorRequest.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_MOTORREQUEST_H
#define JETBOTMINI_MSGS_MESSAGE_MOTORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbotmini_msgs
{
template <class ContainerAllocator>
struct MotorRequest_
{
  typedef MotorRequest_<ContainerAllocator> Type;

  MotorRequest_()
    : rightspeed(0.0)
    , leftspeed(0.0)  {
    }
  MotorRequest_(const ContainerAllocator& _alloc)
    : rightspeed(0.0)
    , leftspeed(0.0)  {
  (void)_alloc;
    }



   typedef float _rightspeed_type;
  _rightspeed_type rightspeed;

   typedef float _leftspeed_type;
  _leftspeed_type leftspeed;





  typedef boost::shared_ptr< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MotorRequest_

typedef ::jetbotmini_msgs::MotorRequest_<std::allocator<void> > MotorRequest;

typedef boost::shared_ptr< ::jetbotmini_msgs::MotorRequest > MotorRequestPtr;
typedef boost::shared_ptr< ::jetbotmini_msgs::MotorRequest const> MotorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetbotmini_msgs::MotorRequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::MotorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.rightspeed == rhs.rightspeed &&
    lhs.leftspeed == rhs.leftspeed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetbotmini_msgs::MotorRequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::MotorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetbotmini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78334da0d98ee6f951a6eca6d3dc6313";
  }

  static const char* value(const ::jetbotmini_msgs::MotorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78334da0d98ee6f9ULL;
  static const uint64_t static_value2 = 0x51a6eca6d3dc6313ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbotmini_msgs/MotorRequest";
  }

  static const char* value(const ::jetbotmini_msgs::MotorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"float32 rightspeed\n"
"float32 leftspeed\n"
;
  }

  static const char* value(const ::jetbotmini_msgs::MotorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rightspeed);
      stream.next(m.leftspeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbotmini_msgs::MotorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbotmini_msgs::MotorRequest_<ContainerAllocator>& v)
  {
    s << indent << "rightspeed: ";
    Printer<float>::stream(s, indent + "  ", v.rightspeed);
    s << indent << "leftspeed: ";
    Printer<float>::stream(s, indent + "  ", v.leftspeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_MOTORREQUEST_H
