// Generated by gencpp from file jetbotmini_msgs/Patrol.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_PATROL_H
#define JETBOTMINI_MSGS_MESSAGE_PATROL_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/PatrolRequest.h>
#include <jetbotmini_msgs/PatrolResponse.h>


namespace jetbotmini_msgs
{

struct Patrol
{

typedef PatrolRequest Request;
typedef PatrolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Patrol
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::Patrol > {
  static const char* value()
  {
    return "58305e3e8d6898838f33185040fe9ed3";
  }

  static const char* value(const ::jetbotmini_msgs::Patrol&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::Patrol > {
  static const char* value()
  {
    return "jetbotmini_msgs/Patrol";
  }

  static const char* value(const ::jetbotmini_msgs::Patrol&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::PatrolRequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Patrol >
template<>
struct MD5Sum< ::jetbotmini_msgs::PatrolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Patrol >::value();
  }
  static const char* value(const ::jetbotmini_msgs::PatrolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::PatrolRequest> should match
// service_traits::DataType< ::jetbotmini_msgs::Patrol >
template<>
struct DataType< ::jetbotmini_msgs::PatrolRequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Patrol >::value();
  }
  static const char* value(const ::jetbotmini_msgs::PatrolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::PatrolResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Patrol >
template<>
struct MD5Sum< ::jetbotmini_msgs::PatrolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Patrol >::value();
  }
  static const char* value(const ::jetbotmini_msgs::PatrolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::PatrolResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::Patrol >
template<>
struct DataType< ::jetbotmini_msgs::PatrolResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Patrol >::value();
  }
  static const char* value(const ::jetbotmini_msgs::PatrolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_PATROL_H
