// Generated by gencpp from file jetbotmini_msgs/PatrolRequest.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_PATROLREQUEST_H
#define JETBOTMINI_MSGS_MESSAGE_PATROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbotmini_msgs
{
template <class ContainerAllocator>
struct PatrolRequest_
{
  typedef PatrolRequest_<ContainerAllocator> Type;

  PatrolRequest_()
    : SetLoop(false)
    , Commond()
    , length(0.0)
    , speed(0.0)
    , laserDistance(0.0)
    , laserAngle(0)  {
    }
  PatrolRequest_(const ContainerAllocator& _alloc)
    : SetLoop(false)
    , Commond(_alloc)
    , length(0.0)
    , speed(0.0)
    , laserDistance(0.0)
    , laserAngle(0)  {
  (void)_alloc;
    }



   typedef uint8_t _SetLoop_type;
  _SetLoop_type SetLoop;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Commond_type;
  _Commond_type Commond;

   typedef float _length_type;
  _length_type length;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _laserDistance_type;
  _laserDistance_type laserDistance;

   typedef int32_t _laserAngle_type;
  _laserAngle_type laserAngle;





  typedef boost::shared_ptr< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolRequest_

typedef ::jetbotmini_msgs::PatrolRequest_<std::allocator<void> > PatrolRequest;

typedef boost::shared_ptr< ::jetbotmini_msgs::PatrolRequest > PatrolRequestPtr;
typedef boost::shared_ptr< ::jetbotmini_msgs::PatrolRequest const> PatrolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator2> & rhs)
{
  return lhs.SetLoop == rhs.SetLoop &&
    lhs.Commond == rhs.Commond &&
    lhs.length == rhs.length &&
    lhs.speed == rhs.speed &&
    lhs.laserDistance == rhs.laserDistance &&
    lhs.laserAngle == rhs.laserAngle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetbotmini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a4edaad5e237a9c19ba9256ad3b5895";
  }

  static const char* value(const ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a4edaad5e237a9cULL;
  static const uint64_t static_value2 = 0x19ba9256ad3b5895ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbotmini_msgs/PatrolRequest";
  }

  static const char* value(const ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"bool    SetLoop\n"
"string  Commond\n"
"float32 length\n"
"float32 speed\n"
"float32 laserDistance\n"
"int32   laserAngle\n"
;
  }

  static const char* value(const ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SetLoop);
      stream.next(m.Commond);
      stream.next(m.length);
      stream.next(m.speed);
      stream.next(m.laserDistance);
      stream.next(m.laserAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbotmini_msgs::PatrolRequest_<ContainerAllocator>& v)
  {
    s << indent << "SetLoop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SetLoop);
    s << indent << "Commond: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Commond);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "laserDistance: ";
    Printer<float>::stream(s, indent + "  ", v.laserDistance);
    s << indent << "laserAngle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.laserAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_PATROLREQUEST_H
