// Generated by gencpp from file jetbotmini_msgs/PatrolWarning.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_PATROLWARNING_H
#define JETBOTMINI_MSGS_MESSAGE_PATROLWARNING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbotmini_msgs
{
template <class ContainerAllocator>
struct PatrolWarning_
{
  typedef PatrolWarning_<ContainerAllocator> Type;

  PatrolWarning_()
    : warning(0)
    , SetLoop(false)
    , close(false)  {
    }
  PatrolWarning_(const ContainerAllocator& _alloc)
    : warning(0)
    , SetLoop(false)
    , close(false)  {
  (void)_alloc;
    }



   typedef int32_t _warning_type;
  _warning_type warning;

   typedef uint8_t _SetLoop_type;
  _SetLoop_type SetLoop;

   typedef uint8_t _close_type;
  _close_type close;





  typedef boost::shared_ptr< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolWarning_

typedef ::jetbotmini_msgs::PatrolWarning_<std::allocator<void> > PatrolWarning;

typedef boost::shared_ptr< ::jetbotmini_msgs::PatrolWarning > PatrolWarningPtr;
typedef boost::shared_ptr< ::jetbotmini_msgs::PatrolWarning const> PatrolWarningConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator2> & rhs)
{
  return lhs.warning == rhs.warning &&
    lhs.SetLoop == rhs.SetLoop &&
    lhs.close == rhs.close;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetbotmini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51654651f81a5e9bee47c3e8eb6bbc5a";
  }

  static const char* value(const ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51654651f81a5e9bULL;
  static const uint64_t static_value2 = 0xee47c3e8eb6bbc5aULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbotmini_msgs/PatrolWarning";
  }

  static const char* value(const ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 warning\n"
"bool  SetLoop\n"
"bool  close\n"
;
  }

  static const char* value(const ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.warning);
      stream.next(m.SetLoop);
      stream.next(m.close);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolWarning_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbotmini_msgs::PatrolWarning_<ContainerAllocator>& v)
  {
    s << indent << "warning: ";
    Printer<int32_t>::stream(s, indent + "  ", v.warning);
    s << indent << "SetLoop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SetLoop);
    s << indent << "close: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.close);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_PATROLWARNING_H
