// Generated by gencpp from file jetbotmini_msgs/RGBLight.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_RGBLIGHT_H
#define JETBOTMINI_MSGS_MESSAGE_RGBLIGHT_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/RGBLightRequest.h>
#include <jetbotmini_msgs/RGBLightResponse.h>


namespace jetbotmini_msgs
{

struct RGBLight
{

typedef RGBLightRequest Request;
typedef RGBLightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RGBLight
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::RGBLight > {
  static const char* value()
  {
    return "4abffe91f7c3570fa771519fedadcf37";
  }

  static const char* value(const ::jetbotmini_msgs::RGBLight&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::RGBLight > {
  static const char* value()
  {
    return "jetbotmini_msgs/RGBLight";
  }

  static const char* value(const ::jetbotmini_msgs::RGBLight&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::RGBLightRequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::RGBLight >
template<>
struct MD5Sum< ::jetbotmini_msgs::RGBLightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::RGBLight >::value();
  }
  static const char* value(const ::jetbotmini_msgs::RGBLightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::RGBLightRequest> should match
// service_traits::DataType< ::jetbotmini_msgs::RGBLight >
template<>
struct DataType< ::jetbotmini_msgs::RGBLightRequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::RGBLight >::value();
  }
  static const char* value(const ::jetbotmini_msgs::RGBLightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::RGBLightResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::RGBLight >
template<>
struct MD5Sum< ::jetbotmini_msgs::RGBLightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::RGBLight >::value();
  }
  static const char* value(const ::jetbotmini_msgs::RGBLightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::RGBLightResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::RGBLight >
template<>
struct DataType< ::jetbotmini_msgs::RGBLightResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::RGBLight >::value();
  }
  static const char* value(const ::jetbotmini_msgs::RGBLightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_RGBLIGHT_H
