// Generated by gencpp from file jetbotmini_msgs/RobotArm.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_ROBOTARM_H
#define JETBOTMINI_MSGS_MESSAGE_ROBOTARM_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/RobotArmRequest.h>
#include <jetbotmini_msgs/RobotArmResponse.h>


namespace jetbotmini_msgs
{

struct RobotArm
{

typedef RobotArmRequest Request;
typedef RobotArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotArm
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::RobotArm > {
  static const char* value()
  {
    return "02b16e175f9698037e15289959eba75b";
  }

  static const char* value(const ::jetbotmini_msgs::RobotArm&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::RobotArm > {
  static const char* value()
  {
    return "jetbotmini_msgs/RobotArm";
  }

  static const char* value(const ::jetbotmini_msgs::RobotArm&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::RobotArmRequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::RobotArm >
template<>
struct MD5Sum< ::jetbotmini_msgs::RobotArmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::RobotArm >::value();
  }
  static const char* value(const ::jetbotmini_msgs::RobotArmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::RobotArmRequest> should match
// service_traits::DataType< ::jetbotmini_msgs::RobotArm >
template<>
struct DataType< ::jetbotmini_msgs::RobotArmRequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::RobotArm >::value();
  }
  static const char* value(const ::jetbotmini_msgs::RobotArmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::RobotArmResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::RobotArm >
template<>
struct MD5Sum< ::jetbotmini_msgs::RobotArmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::RobotArm >::value();
  }
  static const char* value(const ::jetbotmini_msgs::RobotArmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::RobotArmResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::RobotArm >
template<>
struct DataType< ::jetbotmini_msgs::RobotArmResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::RobotArm >::value();
  }
  static const char* value(const ::jetbotmini_msgs::RobotArmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_ROBOTARM_H
