// Generated by gencpp from file jetbotmini_msgs/ServoRequest.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_SERVOREQUEST_H
#define JETBOTMINI_MSGS_MESSAGE_SERVOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetbotmini_msgs
{
template <class ContainerAllocator>
struct ServoRequest_
{
  typedef ServoRequest_<ContainerAllocator> Type;

  ServoRequest_()
    : servoid(0)
    , angle(0)  {
    }
  ServoRequest_(const ContainerAllocator& _alloc)
    : servoid(0)
    , angle(0)  {
  (void)_alloc;
    }



   typedef int32_t _servoid_type;
  _servoid_type servoid;

   typedef int32_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServoRequest_

typedef ::jetbotmini_msgs::ServoRequest_<std::allocator<void> > ServoRequest;

typedef boost::shared_ptr< ::jetbotmini_msgs::ServoRequest > ServoRequestPtr;
typedef boost::shared_ptr< ::jetbotmini_msgs::ServoRequest const> ServoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetbotmini_msgs::ServoRequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::ServoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.servoid == rhs.servoid &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetbotmini_msgs::ServoRequest_<ContainerAllocator1> & lhs, const ::jetbotmini_msgs::ServoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetbotmini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9725c22557a406cf728ce6094df5e71e";
  }

  static const char* value(const ::jetbotmini_msgs::ServoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9725c22557a406cfULL;
  static const uint64_t static_value2 = 0x728ce6094df5e71eULL;
};

template<class ContainerAllocator>
struct DataType< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetbotmini_msgs/ServoRequest";
  }

  static const char* value(const ::jetbotmini_msgs::ServoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"int32 servoid\n"
"int32 angle\n"
;
  }

  static const char* value(const ::jetbotmini_msgs::ServoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servoid);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetbotmini_msgs::ServoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetbotmini_msgs::ServoRequest_<ContainerAllocator>& v)
  {
    s << indent << "servoid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.servoid);
    s << indent << "angle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_SERVOREQUEST_H
