// Generated by gencpp from file jetbotmini_msgs/Servo.msg
// DO NOT EDIT!


#ifndef JETBOTMINI_MSGS_MESSAGE_SERVO_H
#define JETBOTMINI_MSGS_MESSAGE_SERVO_H

#include <ros/service_traits.h>


#include <jetbotmini_msgs/ServoRequest.h>
#include <jetbotmini_msgs/ServoResponse.h>


namespace jetbotmini_msgs
{

struct Servo
{

typedef ServoRequest Request;
typedef ServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Servo
} // namespace jetbotmini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetbotmini_msgs::Servo > {
  static const char* value()
  {
    return "ec6b8e444e275e14bfe3fc52ab8f747e";
  }

  static const char* value(const ::jetbotmini_msgs::Servo&) { return value(); }
};

template<>
struct DataType< ::jetbotmini_msgs::Servo > {
  static const char* value()
  {
    return "jetbotmini_msgs/Servo";
  }

  static const char* value(const ::jetbotmini_msgs::Servo&) { return value(); }
};


// service_traits::MD5Sum< ::jetbotmini_msgs::ServoRequest> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Servo >
template<>
struct MD5Sum< ::jetbotmini_msgs::ServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Servo >::value();
  }
  static const char* value(const ::jetbotmini_msgs::ServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::ServoRequest> should match
// service_traits::DataType< ::jetbotmini_msgs::Servo >
template<>
struct DataType< ::jetbotmini_msgs::ServoRequest>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Servo >::value();
  }
  static const char* value(const ::jetbotmini_msgs::ServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetbotmini_msgs::ServoResponse> should match
// service_traits::MD5Sum< ::jetbotmini_msgs::Servo >
template<>
struct MD5Sum< ::jetbotmini_msgs::ServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetbotmini_msgs::Servo >::value();
  }
  static const char* value(const ::jetbotmini_msgs::ServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetbotmini_msgs::ServoResponse> should match
// service_traits::DataType< ::jetbotmini_msgs::Servo >
template<>
struct DataType< ::jetbotmini_msgs::ServoResponse>
{
  static const char* value()
  {
    return DataType< ::jetbotmini_msgs::Servo >::value();
  }
  static const char* value(const ::jetbotmini_msgs::ServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETBOTMINI_MSGS_MESSAGE_SERVO_H
