# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jetbotmini_msgs/PatrolWarning.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PatrolWarning(genpy.Message):
  _md5sum = "51654651f81a5e9bee47c3e8eb6bbc5a"
  _type = "jetbotmini_msgs/PatrolWarning"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 warning
bool  SetLoop
bool  close"""
  __slots__ = ['warning','SetLoop','close']
  _slot_types = ['int32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       warning,SetLoop,close

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PatrolWarning, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.warning is None:
        self.warning = 0
      if self.SetLoop is None:
        self.SetLoop = False
      if self.close is None:
        self.close = False
    else:
      self.warning = 0
      self.SetLoop = False
      self.close = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2B().pack(_x.warning, _x.SetLoop, _x.close))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.warning, _x.SetLoop, _x.close,) = _get_struct_i2B().unpack(str[start:end])
      self.SetLoop = bool(self.SetLoop)
      self.close = bool(self.close)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2B().pack(_x.warning, _x.SetLoop, _x.close))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.warning, _x.SetLoop, _x.close,) = _get_struct_i2B().unpack(str[start:end])
      self.SetLoop = bool(self.SetLoop)
      self.close = bool(self.close)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2B = None
def _get_struct_i2B():
    global _struct_i2B
    if _struct_i2B is None:
        _struct_i2B = struct.Struct("<i2B")
    return _struct_i2B
